// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using reservation_system_for_padel.Services;

#nullable disable

namespace reservation_system_for_padel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915190609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("reservation_system_for_padel.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Number = 3
                        });
                });

            modelBuilder.Entity("reservation_system_for_padel.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourtId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("UserId");

                    b.HasIndex("CourtId", "Date", "TimeSlotId")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("reservation_system_for_padel.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeOnly(9, 0, 0),
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeOnly(10, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeOnly(11, 0, 0),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeOnly(12, 0, 0),
                            StartTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new TimeOnly(13, 0, 0),
                            StartTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new TimeOnly(14, 0, 0),
                            StartTime = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            EndTime = new TimeOnly(15, 0, 0),
                            StartTime = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            EndTime = new TimeOnly(16, 0, 0),
                            StartTime = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            EndTime = new TimeOnly(17, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            EndTime = new TimeOnly(19, 0, 0),
                            StartTime = new TimeOnly(18, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            EndTime = new TimeOnly(21, 0, 0),
                            StartTime = new TimeOnly(20, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            EndTime = new TimeOnly(22, 0, 0),
                            StartTime = new TimeOnly(21, 0, 0)
                        });
                });

            modelBuilder.Entity("reservation_system_for_padel.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("reservation_system_for_padel.Models.Reservation", b =>
                {
                    b.HasOne("reservation_system_for_padel.Models.Court", "Court")
                        .WithMany("Reservations")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reservation_system_for_padel.Models.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("reservation_system_for_padel.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("TimeSlot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("reservation_system_for_padel.Models.Court", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("reservation_system_for_padel.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
